# Generated by Django 3.0.5 on 2022-03-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar_default.png', upload_to='profile_pictures'),
        ),
    ]
