# Generated by Django 3.0.5 on 2022-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_enabled', models.BooleanField(default=True)),
                ('chat_friends_only', models.BooleanField(default=False)),
                ('posts_friends_only', models.BooleanField(default=False)),
            ],
        ),
    ]
