# Generated by Django 3.0.5 on 2022-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
