# Generated by Django 3.0.5 on 2022-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_configuration_comments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='management_token',
            field=models.CharField(default='changeme', max_length=100),
        ),
    ]
