# Generated by Django 3.0.5 on 2022-09-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_configuration_management_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='profiles_friends_only',
            field=models.BooleanField(default=False),
        ),
    ]
