# Generated by Django 3.0.5 on 2022-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_configuration_relationship_management_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='registration_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
