# Generated by Django 3.0.5 on 2023-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_configuration_registration_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='comments_friends_only',
            field=models.BooleanField(default=False),
        ),
    ]
