# Generated by Django 3.0.5 on 2022-03-14 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20220314_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='clicked',
            new_name='user_clicked',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisements', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
