# Generated by Django 3.0.5 on 2022-04-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20220329_0050'),
        ('posts', '0004_auto_20220314_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_sessions', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedPostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.BigIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_views', to='posts.Post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_post_views', to='profiles.Profile')),
            ],
        ),
    ]
