# Generated by Django 3.0.5 on 2022-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackedsession',
            old_name='start',
            new_name='first_seen',
        ),
    ]
