# Generated by Django 3.0.5 on 2022-04-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20220420_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackedpostview',
            old_name='total_time',
            new_name='total_time_ms',
        ),
    ]
