# Generated by Django 3.0.5 on 2022-03-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
        ('posts', '0003_auto_20220311_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unlike',
            new_name='Dislike',
        ),
    ]
