# Generated by Django 3.0.5 on 2022-09-02 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220329_0050'),
        ('posts', '0004_auto_20220314_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='like',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PlannedReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_delta', models.IntegerField(default=0)),
                ('reaction_type', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=8)),
                ('post_offset', models.IntegerField(blank=True, default=0)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('target_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_profile', to='profiles.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
