# Generated by Django 3.0.5 on 2022-09-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220329_0050'),
        ('posts', '0005_auto_20220902_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedreaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='plannedreaction',
            name='target_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_profile', to='profiles.Profile'),
        ),
    ]
