# Generated by Django 3.0.5 on 2023-10-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220902_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
